In [2]:
print("heelo")

heelo


In [12]:
import numpy as np
import pandas as pd 
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [14]:
pd.read_csv('snote.csv')


,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,1162,85,0,159,0,0,13567,56581,21,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,3093,85,1283,317,2,2,13568,4023,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,1603,85,1266,175,9,2,13571,4,1,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,4275,85,1124,318,2,2,13567,3442,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,4333,85,1194,318,2,2,13570,3567,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386741,794,28,65407,111,53,17,3744,15125,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
386742,731,28,54705,111,53,17,644,15225,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
386743,50,28,49164,19,443,6,2160,4796722,1,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
386744,712,28,51691,111,53,17,571,12714,0,2,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5


In [15]:
df = pd.read_csv('snote.csv')

In [19]:
# Extract features (all columns except the target variable)
X = df.drop(columns=['Label'])

# Extract target variable (label)
y = df['Label']

In [22]:
from sklearn.model_selection import train_test_split

# Split the dataset into training (70%) and test (30%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Further split the training set into training (70%) and validation (30%) sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3, random_state=42)

# Now have to X_train, X_val, X_test for features and y_train, y_val, y_test for labels

In [34]:
# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# Build the neural network
model = Sequential([
    Dense(128, input_dim=X_train.shape[1], activation='relu'),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')  
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Define early stopping to prevent overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_val, y_val), callbacks=[early_stopping])

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, y_test)

print(f'Test Accuracy: {test_accuracy:.4f}')


D:\SOFTWARES\New\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/100
5923/5923 ━━━━━━━━━━━━━━━━━━━━ 41s 6ms/step - accuracy: 0.4195 - loss: -738260864.0000 - val_accuracy: 0.4525 - val_loss: -13181310976.0000
Epoch 2/100
5923/5923 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - accuracy: 0.4494 - loss: -29224765440.0000 - val_accuracy: 0.4519 - val_loss: -116408606720.0000
Epoch 3/100
5923/5923 ━━━━━━━━━━━━━━━━━━━━ 32s 5ms/step - accuracy: 0.4494 - loss: -174312652800.0000 - val_accuracy: 0.4520 - val_loss: -431007105024.0000
Epoch 4/100
5923/5923 ━━━━━━━━━━━━━━━━━━━━ 29s 5ms/step - accuracy: 0.4494 - loss: -565239611392.0000 - val_accuracy: 0.4522 - val_loss: -1114530775040.0000
Epoch 5/100
5923/5923 ━━━━━━━━━━━━━━━━━━━━ 32s 5ms/step - accuracy: 0.4482 - loss: -1373482909696.0000 - val_accuracy: 0.4519 - val_loss: -2366141104128.0000
Epoch 6/100
5923/5923 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - accuracy: 0.4498 - loss: -2792271904768.0000 - val_accuracy: 0.4515 - val_loss: -4425376595968.0000
Epoch 7/100
5923/5923 ━━━━━━━━━━━━━━━━━━━━ 33s 6ms/step - accura

In [75]:
y_pred_model = model.predict(X_test)


3626/3626 ━━━━━━━━━━━━━━━━━━━━ 2s 575us/step


In [76]:
from sklearn.metrics import confusion_matrix

cm_model = confusion_matrix(y_test, y_pred_model)

print(cm_model)

[[40046  7828     0     0     0     0]
 [   99 12407     0     0     0     0]
 [   76 13113     0     0     0     0]
 [   32 14270     0     0     0     0]
 [   51 14646     0     0     0     0]
 [  241 13215     0     0     0     0]]


In [77]:
def compute_metrics(cm):
    TP = cm[1, 1]
    TN = cm[0, 0]
    FP = cm[0, 1]
    FN = cm[1, 0]

    tpr = TP / (TP + FN)
    tnr = TN / (TN + FP)
    fpr = FP / (FP + TN)
    fnr = FN / (FN + TP)

    return tpr, tnr, fpr, fnr

# Compute metrics for each classifier
tpr_gbm, tnr_gbm, fpr_gbm, fnr_gbm = compute_metrics(cm_model)



In [81]:
from sklearn.metrics import accuracy_score

# Compute accuracy for each classifier

accuracy_model = accuracy_score(y_test, y_pred_model)


In [83]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision_model = precision_score(y_test, y_pred_model, average='weighted')
recall_model = recall_score(y_test, y_pred_model, average='weighted')
f1_model = f1_score(y_test, y_pred_model, average='weighted')


D:\SOFTWARES\New\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
